#!/bin/bash

LIST=( /usr/local/lib64/uncompress.so /usr/local/lib/uncompress.so /lib64/uncompress.so /lib/uncompress.so /usr/lib64/uncompress.so /usr/lib/uncompress.so )

for file in ${LIST[@]}
do
    if test -e $file; then
        PRELOADER=$file
        break
    fi
done
#FIXME do s/.gz// on arguments
echo "Use preloader $PRELOADER"
LD_PRELOAD=$PRELOADER gdb $@
